export const supabaseUrl = "https://kmninrlubuimhheaegqs.supabase.co"
export const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imttbmlucmx1YnVpbWhoZWFlZ3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NTU5ODksImV4cCI6MjA1OTMzMTk4OX0.WXsBAPBXQBbiI02ywFrgsdQkUmZv8W7gKksJbFTf-4c"
